// <auto-generated />
using System;
using CineReserveAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineReserveAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CineReserveAPI.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A thief who steals corporate secrets through dream-sharing technology.",
                            Duration = 148,
                            Genre = "Sci-Fi / Thriller",
                            PosterUrl = "https://picsum.photos/seed/inception/300/450",
                            Rating = 8.8m,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A team of explorers travel through a wormhole in space to ensure humanity's survival.",
                            Duration = 169,
                            Genre = "Sci-Fi / Adventure",
                            PosterUrl = "https://picsum.photos/seed/interstellar/300/450",
                            Rating = 8.6m,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Batman faces the Joker, a criminal mastermind who creates chaos in Gotham City.",
                            Duration = 152,
                            Genre = "Action / Drama",
                            PosterUrl = "https://picsum.photos/seed/darkknight/300/450",
                            Rating = 9.0m,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The Avengers assemble once more to reverse Thanos' actions.",
                            Duration = 181,
                            Genre = "Action / Adventure",
                            PosterUrl = "https://picsum.photos/seed/avengers/300/450",
                            Rating = 8.4m,
                            Title = "Avengers: Endgame"
                        });
                });

            modelBuilder.Entity("CineReserveAPI.Models.SeatBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("SeatPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShowtimeId")
                        .HasDatabaseName("IX_SeatBookings_ShowtimeId");

                    b.HasIndex("UserId");

                    b.HasIndex("ShowtimeId", "RowLetter", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_SeatBooking_Showtime_Row_Seat");

                    b.ToTable("SeatBookings");
                });

            modelBuilder.Entity("CineReserveAPI.Models.Showtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("HallName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShowDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ShowTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("IX_Showtimes_MovieId");

                    b.ToTable("Showtimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 250m,
                            HallName = "Hall A",
                            MovieId = 1,
                            ShowDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ShowTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 300m,
                            HallName = "Hall B",
                            MovieId = 1,
                            ShowDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ShowTime = new TimeSpan(0, 14, 30, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 350m,
                            HallName = "Hall A",
                            MovieId = 1,
                            ShowDate = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ShowTime = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 280m,
                            HallName = "Hall C",
                            MovieId = 2,
                            ShowDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ShowTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 320m,
                            HallName = "Hall A",
                            MovieId = 2,
                            ShowDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ShowTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 260m,
                            HallName = "Hall B",
                            MovieId = 3,
                            ShowDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ShowTime = new TimeSpan(0, 12, 30, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 380m,
                            HallName = "Hall C",
                            MovieId = 3,
                            ShowDate = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ShowTime = new TimeSpan(0, 20, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 300m,
                            HallName = "Hall A",
                            MovieId = 4,
                            ShowDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ShowTime = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            BasePrice = 350m,
                            HallName = "Hall B",
                            MovieId = 4,
                            ShowDate = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ShowTime = new TimeSpan(0, 19, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("CineReserveAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CreditBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CineReserveAPI.Models.SeatBooking", b =>
                {
                    b.HasOne("CineReserveAPI.Models.Showtime", "Showtime")
                        .WithMany("SeatBookings")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineReserveAPI.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CineReserveAPI.Models.Showtime", b =>
                {
                    b.HasOne("CineReserveAPI.Models.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CineReserveAPI.Models.Movie", b =>
                {
                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("CineReserveAPI.Models.Showtime", b =>
                {
                    b.Navigation("SeatBookings");
                });

            modelBuilder.Entity("CineReserveAPI.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
